- hosts: all
  become: yes
  become_user: root
  tasks:
   - name: install apt
     apt:
      name:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common
  
   - name: add gpg
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg 

   - name: add docker repo
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

   - name: install docker
     apt:
      name:
       - docker-ce
       - docker-ce-cli
       - containerd.io

   - name: Install docker-compose
     get_url:
      url : https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
